version: "3.8"
services:
  mongo:
    image: mongo
    container_name: "eafc24-tournament-mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./mongo:/data/db"
    ports:
      - 27100:27017
